package _6_binary_tree

/*
144. 二叉树的前序遍历 / Binary Tree Preorder Traversal
题目描述 / Problem Description
给定二叉树根节点 root，返回节点值的前序遍历结果。
Given the root of a binary tree, return its preorder traversal.
前序遍历顺序：
Preorder traversal order:
根 → 左 → 右
Root → Left → Right
解题思路 / Solution Approach
使用栈保存等待访问的节点。
Use a stack to store nodes waiting to be visited.
每次弹出一个节点后：
After popping a node:
1. 访问当前节点；
   Visit the current node;
2. 先将右子节点压栈；
   Push the right child first;
3. 再将左子节点压栈。
   Push the left child second.
因为栈是后进先出，所以左子节点会先被处理。
Because the stack is LIFO, the left child is processed first.

递归法 / Recursive method:
traverse(node) 的任务是按指定顺序访问 node 的整棵子树，而不只是访问一个节点。
空节点直接返回；前序在递归左右子树前记录根，中序在两次递归之间记录根，后序在两次递归后记录根。
每次递归返回时，该子树已经全部处理完，所以根的记录位置决定了三种遍历顺序。
traverse(node) visits the entire subtree, not just one node. Return on nil.
Record the root before both child calls for preorder, between them for inorder, or after both for postorder.
Each call finishes its whole subtree before returning, so the position of the root visit determines the traversal order.

前序为什么能处理完整左子树再处理右子树？右孩子先压在下面，处理左孩子时产生的后续节点都压在它上面，
因此这些左子树节点会先被弹出，而不只是左孩子一个节点先被访问。
Why does preorder finish the entire left subtree first? The right child is pushed underneath;
all work generated by the left subtree is pushed above it and therefore popped first.

本文件包含的实现 / Implementations in This File
前序与中序各四种写法（专用迭代、递归、统一迭代、Morris），后序三种（反转法迭代、递归、统一迭代），共十一个函数。
Preorder and inorder each have four forms (dedicated iteration, recursion, unified iteration, and Morris),
while postorder has three (reversal-based iteration, recursion, and unified iteration), for eleven functions in total.
- 前序 / Preorder: preorderTraversal（专用迭代）、preorderTraversalRecursive、preorderTraversalUnified、preorderTraversalMorris
- 中序 / Inorder: inorderTraversal（专用迭代）、inorderTraversalRecursive、inorderTraversalUnified、inorderTraversalMorris
- 后序 / Postorder: postorderTraversal（反转法迭代）、postorderTraversalRecursive、postorderTraversalUnified
Morris 后序需要额外反转一条右边界链，写法明显更复杂，本文件不收录。
Morris postorder requires reversing a right-boundary chain and is noticeably more involved, so it is omitted here.

时间与空间复杂度 / Time and Space Complexity
n 为节点数，h 为树高。所有写法时间均为 O(n)；后序迭代额外反转 O(n)，统一写法把每个节点最多入栈两次，
Morris 沿左子树右边界重复下降，都只改变常数，不改变线性阶。
辅助空间：递归与专用迭代、统一写法均为 O(h)，包括显式栈或递归调用栈；
平衡树 h=O(log n)，最坏 h=n。显式栈可保存路径上的待访问兄弟节点，并非只保存一条路径本身。
统一写法的栈里还混有 nil 标记，数量与节点同阶，因此仍是 O(h)。
Morris 只用几个指针，辅助空间 O(1)，代价是临时改写右指针。
每种解法返回结果占 O(n)，包含结果的总空间 O(n)。
For n nodes and height h, every form takes O(n) time. Reversing iterative postorder adds O(n),
the unified form pushes each node at most twice, and Morris re-descends right boundaries of left subtrees;
all three affect only constants, not the linear order.
Auxiliary space is O(h) for recursion, the dedicated iterative forms, and the unified form, covering explicit
or recursive stacks; h=O(log n) for a balanced tree and up to n otherwise.
Explicit stacks may hold pending siblings along a path, not just the path itself.
The unified stack also interleaves nil markers, which stay proportional to the nodes on that path, so it remains O(h).
Morris uses only a few pointers for O(1) auxiliary space, at the cost of temporarily rewriting right pointers.
Each output and total space take O(n).
*/

/*
题目描述 / Problem Description

返回二叉树的前序遍历结果。
Return the preorder traversal of a binary tree.

解题思路 / Solution Approach

使用栈按照“根、左、右”的顺序访问节点。
Use a stack to visit nodes in root-left-right order.

因为栈是后进先出，所以先压入右子节点，再压入左子节点。
Because the stack is LIFO, push the right child before the left child.
*/

// 1. 前序专用迭代：先压右孩子，再压左孩子
func preorderTraversal(root *TreeNode) []int {
	// An empty tree has no traversal result.
	// 空树没有遍历结果。
	if root == nil {
		return []int{}
	}

	result := make([]int, 0)
	stack := []*TreeNode{root}

	for len(stack) > 0 {
		// Pop the top node.
		// 弹出栈顶节点。
		last := len(stack) - 1
		node := stack[last]
		stack = stack[:last]

		// Visit the root before its children.
		// 在左右子节点之前访问根节点。
		result = append(result, node.Val)

		// Push right first so it is processed after the left child.
		// 先压入右子节点，使它在左子节点之后处理。
		if node.Right != nil {
			stack = append(stack, node.Right)
		}

		// Push left last so it is processed next.
		// 后压入左子节点，使它下一步被处理。
		if node.Left != nil {
			stack = append(stack, node.Left)
		}
	}

	return result
}

// 2. 前序递归：在两次递归之前记录根
func preorderTraversalRecursive(root *TreeNode) []int {
	result := make([]int, 0)

	var traverse func(*TreeNode)
	traverse = func(node *TreeNode) {
		if node == nil {
			return
		}

		// Root → Left → Right
		// 根 → 左 → 右
		result = append(result, node.Val)
		traverse(node.Left)
		traverse(node.Right)
	}

	traverse(root)
	return result
}

/*
94. 二叉树的中序遍历 / Binary Tree Inorder Traversal

题目描述 / Problem Description
给定二叉树根节点 root，返回按照“左、根、右”顺序访问的节点值。
Given the root of a binary tree, return its node values in left-root-right order.

解题思路 / Solution Approach
迭代法沿左侧路径不断压栈；无法继续向左时，弹出并访问栈顶节点，再进入其右子树。
The iterative solution pushes nodes along the left path. When no further left node exists,
pop and visit the top node, then enter its right subtree.

为什么先压栈不立即记录？入栈表示“记住这个根，等左子树处理完再访问”，不是已经访问它。
current=nil 只表示这条向左路径走到底，栈里可能仍有等待访问的根，所以外层条件用 || 而不是 &&。
弹出栈顶时，其左子树已处理完；记录它，再转向右子树，恰好实现左、根、右。
例如根 2、左孩子 1、右孩子 3：先压 2、1，弹 1 记录，再弹 2 记录，最后进入 3，得到 [1,2,3]。
递归版本同理：左子树调用完成后记录根，再调用右子树。
Pushing saves a root for later; it does not visit it. current=nil ends a leftward path, but saved roots may remain,
so the outer condition uses || rather than &&. A popped node has finished its left subtree; visit it, then enter its right subtree.
For root 2 with children 1 and 3, push 2 then 1, visit popped 1 then 2, then enter 3, producing [1,2,3].
The recursive version likewise records the root after the left call returns and before the right call.

// Ordinary tree:
	// 普通二叉树：
	//
	//          1
	//        /   \
	//       2     3
	//      / \     \
	//     4   5     6
*/

// 1. 中序专用迭代：沿左侧压栈，弹出时记录
func inorderTraversal(root *TreeNode) []int {
	result := make([]int, 0)
	stack := make([]*TreeNode, 0)
	current := root

	// Continue while an unexplored node or a saved ancestor remains.
	// 只要还有未探索节点或栈中还有祖先节点，就继续处理。
	for current != nil || len(stack) > 0 {
		// Reach the leftmost node and save every ancestor on the path.
		// 不断向左移动，并保存路径上的每个祖先节点。
		for current != nil {
			stack = append(stack, current)
			current = current.Left
		}

		last := len(stack) - 1
		current = stack[last]
		stack = stack[:last]

		// Visit the root after its left subtree.
		// 左子树处理完成后访问根节点。
		result = append(result, current.Val)
		current = current.Right
	}

	return result
}

// 2. 中序递归：在两次递归之间记录根
func inorderTraversalRecursive(root *TreeNode) []int {
	result := make([]int, 0)

	var traverse func(*TreeNode)
	traverse = func(node *TreeNode) {
		if node == nil {
			return
		}

		// Left -> Root -> Right
		// 左 -> 根 -> 右
		traverse(node.Left)
		result = append(result, node.Val)
		traverse(node.Right)
	}

	traverse(root)
	return result
}

/*
145. 二叉树的后序遍历 / Binary Tree Postorder Traversal

题目描述 / Problem Description
给定二叉树根节点 root，返回按照“左、右、根”顺序访问的节点值。
Given the root of a binary tree, return its node values in left-right-root order.

解题思路 / Solution Approach
迭代法先通过栈得到“根、右、左”的顺序，再反转结果得到“左、右、根”。
The iterative solution first produces root-right-left order with a stack, then reverses it to obtain left-right-root order.

这里的左、右指整棵子树的访问序列。反转“根 + 右子树序列 + 左子树序列”后，变成
“反转后的左子树序列 + 反转后的右子树序列 + 根”；每棵子树内部也遵守同样规则，所以整体才是真正的后序。
例如根 1、左孩子 2（它的孩子是 4、5）、右孩子 3：临时结果 [1,3,2,5,4]，反转为 [4,5,2,3,1]。
递归版本不需要反转：左右子树递归都返回后再记录根，此时它们已经按后序处理完成。
Left and right denote whole subtree sequences. Reversing root + right-sequence + left-sequence gives
reversed-left + reversed-right + root. Each subtree follows the same rule, so the whole result is postorder.
For root 1, left child 2 with children 4 and 5, and right child 3: [1,3,2,5,4] reverses to [4,5,2,3,1].
Recursion needs no reversal: record the root only after both subtree calls have completed their postorder visits.
*/

// 1. 后序迭代：先得到“根、右、左”，再整体反转
func postorderTraversal(root *TreeNode) []int {
	if root == nil {
		return []int{}
	}

	result := make([]int, 0)
	stack := []*TreeNode{root}

	for len(stack) > 0 {
		last := len(stack) - 1
		node := stack[last]
		stack = stack[:last]

		// Temporarily record nodes in root-right-left order.
		// 暂时按照“根、右、左”的顺序记录节点。
		result = append(result, node.Val)

		// Push left before right so right is processed first.
		// 先压入左子节点、再压入右子节点，使右子节点先处理。
		if node.Left != nil {
			stack = append(stack, node.Left)
		}
		if node.Right != nil {
			stack = append(stack, node.Right)
		}
	}

	// Reverse root-right-left into left-right-root.
	// 将“根、右、左”反转为“左、右、根”。
	for left, right := 0, len(result)-1; left < right; left, right = left+1, right-1 {
		result[left], result[right] = result[right], result[left]
	}
	/*	// 项目代码更简洁
		// More concise for project code.
		slices.Reverse(result)
	*/

	return result
}

// 2. 后序递归：在两次递归之后记录根
func postorderTraversalRecursive(root *TreeNode) []int {
	result := make([]int, 0)

	var traverse func(*TreeNode)
	traverse = func(node *TreeNode) {
		if node == nil {
			return
		}

		// Left -> Right -> Root
		// 左 -> 右 -> 根
		traverse(node.Left)
		traverse(node.Right)
		result = append(result, node.Val)
	}

	traverse(root)
	return result
}

/*
统一迭代法（标记法） / Unified Iteration with nil Markers

为什么需要统一写法 / Why a Unified Form
上面三种专用迭代各用一套模板：前序靠压栈顺序，中序靠沿左侧下降，后序靠反转结果。
换一种遍历就要换一种思路，记忆成本高，而且前序的模板直接改成中序是错的。
统一写法用同一段代码结构表达三种顺序，只调整入栈的先后。
The three dedicated iterative forms above use three different templates: push order for preorder,
left-descent for inorder, and result reversal for postorder.
Switching traversals means switching ideas, and simply reordering the preorder template does not yield inorder.
The unified form expresses all three orders with one code shape, changing only the push order.

核心问题：栈里的节点身份不明 / The Core Problem: Ambiguous Stack Entries
迭代时一个节点会被碰到两次：第一次是“要展开它的子树”，第二次是“可以记录它的值了”。
只存节点指针无法区分这两种身份，所以中序不能照抄前序模板。
An iterative traversal meets each node twice: once to expand its subtree and once to record its value.
A bare node pointer cannot distinguish these two roles, which is why inorder cannot copy the preorder template.

解决办法：紧跟一个 nil 标记 / The Fix: Append a nil Marker
约定“节点 + 紧跟其后的 nil”表示这个节点只需记录，不再展开。
因为栈是后进先出，nil 压在节点上面，所以弹出 nil 之后，下一个弹出的就是待记录的节点。
弹出非 nil 节点时，说明它还没展开：按“期望顺序的逆序”把它的孩子和它自己（带标记）压入栈。
Adopt the convention that a node immediately followed by nil means "record only, do not expand".
Because the stack is LIFO, the nil sits above its node, so the pop after a nil yields the node to record.
Popping a non-nil node means it is still unexpanded: push its children and itself (with a marker)
in the reverse of the desired order.

三种顺序只差入栈次序 / Only the Push Order Differs
期望顺序 / Desired order      入栈次序 / Push order
根 左 右 / Root Left Right    右、左、根+nil / right, left, root+nil
左 根 右 / Left Root Right    右、根+nil、左 / right, root+nil, left
左 右 根 / Left Right Root    根+nil、右、左 / root+nil, right, left
空孩子不入栈，否则会和表示“待记录”的 nil 标记混淆；根为 nil 时栈保持为空，直接返回空结果。
Do not push nil children, which would be indistinguishable from the record-marker nil.
A nil root leaves the stack empty and returns an empty result immediately.

时间与空间复杂度 / Time and Space Complexity
n 为节点数，h 为树高。时间 O(n)：每个节点最多入栈两次（一次展开、一次记录），常数不影响线性阶。
辅助空间 O(h)，栈中是一条根到叶路径上的待处理节点及其 nil 标记；最坏 h=n。结果另占 O(n)。
For n nodes and height h, time is O(n): each node is pushed at most twice, once to expand and once to record,
which changes only the constant. Auxiliary space is O(h) for the pending nodes along one root-to-leaf path
plus their nil markers, up to n in the worst case. The output takes a further O(n).
*/

// 3. 前序统一迭代：入栈次序为右、左、根+nil
func preorderTraversalUnified(root *TreeNode) []int {
	result := make([]int, 0)
	stack := []*TreeNode{}

	// Never push a nil child; nil is reserved as the record marker.
	// 不要压入空孩子，nil 已经被约定为“待记录”标记。
	if root != nil {
		stack = append(stack, root)
	}

	for len(stack) > 0 {
		last := len(stack) - 1
		node := stack[last]
		stack = stack[:last]

		// A nil marker means the node underneath it is ready to be recorded.
		// 弹出 nil 标记，说明它下面那个节点已经可以记录了。
		if node == nil {
			last = len(stack) - 1
			node = stack[last]
			stack = stack[:last]
			result = append(result, node.Val)
			continue
		}

		// Push in reverse of root-left-right so the root pops first.
		// 按“根、左、右”的逆序入栈，使根最先弹出。
		if node.Right != nil {
			stack = append(stack, node.Right)
		}
		if node.Left != nil {
			stack = append(stack, node.Left)
		}
		stack = append(stack, node, nil)
	}

	return result
}

// 4. 中序统一迭代：入栈次序为右、根+nil、左
func inorderTraversalUnified(root *TreeNode) []int {
	result := make([]int, 0)
	stack := []*TreeNode{}

	if root != nil {
		stack = append(stack, root)
	}

	for len(stack) > 0 {
		last := len(stack) - 1
		node := stack[last]
		stack = stack[:last]

		// The same marker rule applies to all three orders.
		// 三种顺序共用同一条标记规则。
		if node == nil {
			last = len(stack) - 1
			node = stack[last]
			stack = stack[:last]
			result = append(result, node.Val)
			continue
		}

		// Push in reverse of left-root-right, placing the root between its children.
		// 按“左、根、右”的逆序入栈，让根夹在两个孩子之间。
		if node.Right != nil {
			stack = append(stack, node.Right)
		}
		stack = append(stack, node, nil)
		if node.Left != nil {
			stack = append(stack, node.Left)
		}
	}

	return result
}

// 5. 后序统一迭代：入栈次序为根+nil、右、左
func postorderTraversalUnified(root *TreeNode) []int {
	result := make([]int, 0)
	stack := []*TreeNode{}

	if root != nil {
		stack = append(stack, root)
	}

	for len(stack) > 0 {
		last := len(stack) - 1
		node := stack[last]
		stack = stack[:last]

		if node == nil {
			last = len(stack) - 1
			node = stack[last]
			stack = stack[:last]
			result = append(result, node.Val)
			continue
		}

		// Push in reverse of left-right-root, so no final reversal is needed.
		// 按“左、右、根”的逆序入栈，因此不需要最后再反转结果。
		stack = append(stack, node, nil)
		if node.Right != nil {
			stack = append(stack, node.Right)
		}
		if node.Left != nil {
			stack = append(stack, node.Left)
		}
	}

	return result
}

/*
Morris 遍历：借用右指针当线索 / Morris Traversal: Threading Spare Right Pointers

为什么能做到 O(1) 辅助空间 / Why O(1) Auxiliary Space Is Possible
递归和栈都是为了记住“左子树处理完以后要回到哪个祖先”。
Morris 不再外部保存这条返回路径，而是把它写进树里：让左子树中序的最后一个节点指回当前节点。
一棵有 n 个节点的二叉树共有 n+1 个空指针，这些空位足够临时存放返回信息。
Recursion and stacks exist to remember which ancestor to return to after a left subtree finishes.
Morris stores that return path inside the tree instead: the last inorder node of the left subtree points back
to the current node. A binary tree with n nodes has n+1 nil pointers, enough spare slots to hold that information.

前驱节点 / The Predecessor
当前节点 current 有左子树时，它的中序前驱是左子树中一直沿 Right 走到底的那个节点。
查找时循环条件是 predecessor.Right != nil && predecessor.Right != current：
第二个条件用来识别“这里已经是我们自己建好的线索”，否则会顺着线索绕回 current，形成死循环。
When current has a left child, its inorder predecessor is the node reached by following Right to the end
of that left subtree. The search condition is predecessor.Right != nil && predecessor.Right != current;
the second test recognises a thread we created earlier, without which the walk would loop back to current forever.

两次到达 current / Arriving at current Twice
predecessor.Right == nil：第一次到达。建立线索 predecessor.Right = current，然后进入左子树。
predecessor.Right == current：第二次到达，说明左子树已经走完。拆掉线索，恢复原树形状，再转向右子树。
线索必须拆掉，否则遍历结束后树被永久改坏，也会让后续遍历出现环。
predecessor.Right == nil marks the first arrival: create the thread predecessor.Right = current, then descend left.
predecessor.Right == current marks the second arrival, meaning the left subtree is finished: remove the thread,
restoring the original shape, and move right.
The thread must be removed, or the tree stays permanently corrupted and later traversals would cycle.

前序与中序的唯一区别 / The Only Difference Between Preorder and Inorder
记录时机不同，走法完全相同。
中序在第二次到达 current 时记录，此时左子树已经输出完，符合“左、根、右”。
前序在第一次到达 current 时记录，也就是建立线索之前，符合“根、左、右”。
没有左子树时，两种顺序都直接记录当前值再转向右子树，因为不存在需要等待的左子树。
Only the moment of recording differs; the walk is identical.
Inorder records on the second arrival, after the left subtree has been emitted, matching left-root-right.
Preorder records on the first arrival, just before creating the thread, matching root-left-right.
With no left child, both orders record immediately and move right, because there is no left subtree to wait for.

代价与注意事项 / Costs and Caveats
时间仍是 O(n)，但每个左子树的右边界会被重复走一次，常数大于普通迭代。
辅助空间 O(1)，只用 current 和 predecessor 两个指针。
遍历过程中树被临时改写，因此不是只读操作：并发访问同一棵树，或在遍历中途 panic，都会留下损坏的结构。
Time remains O(n), although the right boundary of each left subtree is walked a second time,
giving a larger constant than the ordinary iterative forms.
Auxiliary space is O(1), using only the current and predecessor pointers.
The tree is temporarily rewritten, so this is not a read-only operation: concurrent access to the same tree,
or a panic partway through, leaves a damaged structure behind.
*/

// 6. 前序 Morris：第一次到达就记录
func preorderTraversalMorris(root *TreeNode) []int {
	result := make([]int, 0)
	current := root

	for current != nil {
		// No left subtree means nothing to wait for, so record and move right.
		// 没有左子树就不需要等待，直接记录并转向右边。
		if current.Left == nil {
			result = append(result, current.Val)
			current = current.Right
			continue
		}

		// Walk to the inorder predecessor: rightmost node of the left subtree.
		// 找中序前驱：左子树中一直沿 Right 走到底的节点。
		predecessor := current.Left

		// The second condition detects a thread we built earlier and avoids a cycle.
		// 第二个条件识别之前建立的线索，避免顺着线索绕回自己造成死循环。
		for predecessor.Right != nil && predecessor.Right != current {
			predecessor = predecessor.Right
		}

		if predecessor.Right == nil {
			// First arrival: preorder records the root before its left subtree.
			// 第一次到达：前序在进入左子树之前记录根。
			result = append(result, current.Val)

			// Store the return path inside an unused nil pointer.
			// 把返回路径写进一个原本为空的右指针里。
			predecessor.Right = current
			current = current.Left
			continue
		}

		// Second arrival: the left subtree is finished, so restore the tree.
		// 第二次到达：左子树已经走完，拆掉线索还原原树。
		predecessor.Right = nil
		current = current.Right
	}

	return result
}

// 7. 中序 Morris：第二次到达才记录
func inorderTraversalMorris(root *TreeNode) []int {
	result := make([]int, 0)
	current := root

	for current != nil {
		// With no left subtree, the current node is already the next inorder value.
		// 没有左子树时，当前节点就是下一个中序值。
		if current.Left == nil {
			result = append(result, current.Val)
			current = current.Right
			continue
		}

		predecessor := current.Left
		for predecessor.Right != nil && predecessor.Right != current {
			predecessor = predecessor.Right
		}

		if predecessor.Right == nil {
			// First arrival: build the thread and descend without recording yet.
			// 第一次到达：建立线索并深入左子树，此时还不能记录。
			predecessor.Right = current
			current = current.Left
			continue
		}

		// Second arrival: remove the thread, then record the root after its left subtree.
		// 第二次到达：先拆掉线索，再在左子树之后记录根，符合“左、根、右”。
		predecessor.Right = nil
		result = append(result, current.Val)
		current = current.Right
	}

	return result
}
